title: "GODAS"
description: >
  CEP Global Ocean Data Assimilation System (GODAS)
recipes:
  - id: "GODASsurface"
    object: "godas:GODASsurface"
  - id: "GODASmulti"
    object: "godas:GODASmulti"
provenance:
  providers:
    - name: "NOAA"
      roles:
        - producer
        - licensor
      url: https://www.cpc.ncep.noaa.gov/products/GODAS/
  license: ""
maintainers:
  - name: "Julius Busecke"
    orcid: "0000-0001-8571-865X"
    github: jbusecke
  - name: "Raphael Hagen"
    orcid: "0000-0003-1994-1153"
    github: norlandrhagen
